
export const products20: Product[] = [
  {
    id: 1,
    img: "/images/Formal-Shirt.jpg",
    name: "Classic White Shirt",
    price: 29.99,
    size: "M",
    originalPrice: 49.99,
  },
  {
    id: 2,
    img: "/images/Formal-Shirt.jpg",
    name: "Slim Fit Navy Shirt",
    price: 34.99,
    size: "L",
    originalPrice: 54.99,
  },
  {
    id: 3,
    img: "/images/Formal-Shirt.jpg",
    name: "Grey Button-Up",
    price: 27.5,
    size: "S",
    originalPrice: 39.99,
  },
  {
    id: 4,
    img: "/images/Formal-Shirt.jpg",
    name: "Striped Office Shirt",
    price: 32.0,
    size: "M",
    originalPrice: 45.0,
  },
  {
    id: 5,
    img: "/images/Formal-Shirt.jpg",
    name: "Sky Blue Shirt",
    price: 30.99,
    size: "XL",
    originalPrice: 49.99,
  },
  {
    id: 6,
    img: "/images/Formal-Shirt.jpg",
    name: "Dark Green Shirt",
    price: 33.49,
    size: "L",
    originalPrice: 50.0,
  },
  {
    id: 7,
    img: "/images/Formal-Shirt.jpg",
    name: "Pinstripe Black Shirt",
    price: 36.0,
    size: "M",
    originalPrice: 60.0,
  },
  {
    id: 8,
    img: "/images/Formal-Shirt.jpg",
    name: "Casual Grey Shirt",
    price: 24.99,
    size: "S",
    originalPrice: 39.99,
  },
  {
    id: 9,
    img: "/images/Formal-Shirt.jpg",
    name: "Checkered Blue Shirt",
    price: 31.99,
    size: "M",
    originalPrice: 49.99,
  },
  {
    id: 10,
    img: "/images/Formal-Shirt.jpg",
    name: "Basic White Shirt",
    price: 22.99,
    size: "M",
    originalPrice: 35.0,
  },

  {
    id: 11,
    img: "/images/Formal-Shirt.jpg",
    name: "Business Black Shirt",
    price: 37.5,
    size: "L",
    originalPrice: 55.0,
  },
  {
    id: 12,
    img: "/images/Formal-Shirt.jpg",
    name: "Cream Casual Shirt",
    price: 26.0,
    size: "S",
    originalPrice: 42.0,
  },
  {
    id: 13,
    img: "/images/Formal-Shirt.jpg",
    name: "Oxford Blue Shirt",
    price: 34.5,
    size: "XL",
    originalPrice: 60.0,
  },
  {
    id: 14,
    img: "/images/Formal-Shirt.jpg",
    name: "Pastel Green Shirt",
    price: 28.99,
    size: "M",
    originalPrice: 44.99,
  },
  {
    id: 15,
    img: "/images/Formal-Shirt.jpg",
    name: "Steel Grey Shirt",
    price: 30.5,
    size: "L",
    originalPrice: 47.99,
  },
  {
    id: 16,
    img: "/images/Formal-Shirt.jpg",
    name: "Fitted White Shirt",
    price: 35.0,
    size: "M",
    originalPrice: 59.99,
  },
  {
    id: 17,
    img: "/images/Formal-Shirt.jpg",
    name: "Light Pink Shirt",
    price: 29.0,
    size: "S",
    originalPrice: 40.0,
  },
  {
    id: 18,
    img: "/images/Formal-Shirt.jpg",
    name: "Graphite Button-Up",
    price: 33.99,
    size: "L",
    originalPrice: 52.0,
  },
  {
    id: 19,
    img: "/images/Formal-Shirt.jpg",
    name: "Mint Green Shirt",
    price: 31.49,
    size: "M",
    originalPrice: 46.99,
  },
  {
    id: 20,
    img: "/images/Formal-Shirt.jpg",
    name: "Ash Grey Shirt",
    price: 25.99,
    size: "XL",
    originalPrice: 39.0,
  },
];
