// src/data/products.ts
import type { Product } from "../types";

export const products: Product[] = [
  {
    id: 1,
    name: "Classic T-shirt",
    price: 25.99,
    img: "/images/T-shirt-1.jpg",
    size: "XXL",
    originalPrice: 30.59,
    color: "Black",
    soldOut: "12.1K+",
  },
  {
    id: 2,
    name: "Blue Jeans",
    price: 45.89,
    img: "/images/jeans.jpeg",
    size: "M",
    originalPrice: 50.99,
    color: "Denim",
    soldOut: "9.3K+",
  },
  {
    id: 3,
    name: "Running Shoes",
    price: 60.29,
    img: "/images/Running-Shoes.jpg",
    size: "S",
    originalPrice: 69.49,
    color: "White",
    soldOut: "15.8K+",
  },
  {
    id: 4,
    name: "Leather Wallet",
    price: 35.59,
    img: "/images/Leather-Wallet.jpg",
    size: "L",
    originalPrice: 38.99,
    color: "Brown",
    soldOut: "3.2K+",
  },
  {
    id: 5,
    name: "Baseball Cap",
    price: 15.89,
    img: "/images/Baseball-Cap.jpg",
    size: "XXL",
    originalPrice: 20.19,
    color: "Grey",
    soldOut: "7.7K+",
  },
  {
    id: 6,
    name: "Winter Jacket",
    price: 90.99,
    img: "/images/Winter-Jacket.jpg",
    size: "XXL",
    originalPrice: 110.79,
    color: "Navy",
    soldOut: "4.5K+",
  },
  {
    id: 7,
    name: "Wrist Watch",
    price: 120.78,
    img: "/images/Wrist-Watch.jpg",
    size: "M",
    originalPrice: 129.89,
    color: "Silver",
    soldOut: "2.1K+",
  },
  {
    id: 8,
    name: "Sunglasses",
    price: 50.69,
    img: "/images/Sunglasses.jpg",
    size: "M",
    originalPrice: 60.88,
    color: "Black",
    soldOut: "10.9K+",
  },
  {
    id: 9,
    name: "Backpack",
    price: 55.29,
    img: "/images/Backpack.jpg",
    size: "XL",
    originalPrice: 60.99,
    color: "Olive",
    soldOut: "5.6K+",
  },
  {
    id: 10,
    name: "Formal Shirt",
    price: 40.39,
    img: "/images/Formal-Shirt.jpg",
    size: "XL",
    originalPrice: 60.89,
    color: "White",
    soldOut: "11.2K+",
  },

  {
    id: 11,
    name: "Sneakers",
    price: 75.89,
    img: "/images/Sneakers.jpg",
    size: "M",
    originalPrice: 85.99,
    color: "Red",
    soldOut: "12.2K+",
  },
  {
    id: 12,
    name: "Beanie Hat",
    price: 18.19,
    img: "/images/Beanie-Hat.jpg",
    size: "L",
    originalPrice: 25.99,
    color: "Green",
    soldOut: "11.5K+",
  },
  {
    id: 13,
    img: "/images/Formal-Shirt.jpg",
    name: "Classic White Shirt",
    price: 29.99,
    size: "M",
    originalPrice: 49.99,
    color: "Purple",
    soldOut: "11.2K+",
  },
  {
    id: 14,
    img: "/images/Formal-Shirt.jpg",
    name: "Slim Fit Navy Shirt",
    price: 34.99,
    size: "L",
    originalPrice: 54.99,
    color: "White",
    soldOut: "2.2K+",
  },
  {
    id: 15,
    img: "/images/Formal-Shirt.jpg",
    name: "Grey Button-Up",
    price: 27.5,
    size: "S",
    originalPrice: 39.99,
    color: "Black",
    soldOut: "1.2K+",
  },
  {
    id: 16,
    img: "/images/Formal-Shirt.jpg",
    name: "Fitted White Shirt",
    price: 35.0,
    size: "M",
    originalPrice: 59.99,
    color: "White",
    soldOut: "6.5K+",
  },
  {
    id: 17,
    img: "/images/Formal-Shirt.jpg",
    name: "Light Pink Shirt",
    price: 29.0,
    size: "S",
    originalPrice: 40.0,
    color: "White",
    soldOut: "29+",
  },
  {
    id: 18,
    img: "/images/Formal-Shirt.jpg",
    name: "Graphite Button-Up",
    price: 33.99,
    size: "L",
    originalPrice: 52.0,
    color: "Navy",
    soldOut: "78+",
  },
  {
    id: 19,
    img: "/images/Formal-Shirt.jpg",
    name: "Mint Green Shirt",
    price: 31.49,
    size: "M",
    originalPrice: 46.99,
    color: "Navi",
    soldOut: "71+",
  },
  {
    id: 20,
    img: "/images/Formal-Shirt.jpg",
    name: "Ash Grey Shirt",
    price: 25.99,
    size: "XL",
    originalPrice: 39.0,
    color: "yellow",
    soldOut: "7+",
  },
  {
    id: 21,
    img: "/items/beige.jpg",
    name: "Beige",
    price: 28.99,
    size: "M",
    originalPrice: 45.0,
    color: "black",
    soldOut: "59+",
  },
  {
    id: 22,
    img: "/items/coffee.jpg",
    name: "Coffee",
    price: 32.5,
    size: "L",
    originalPrice: 50.0,
    color: "Blue",
    soldOut: "18+",
  },
  {
    id: 23,
    img: "/items/khaki.jpg",
    name: "Khaki",
    price: 26.0,
    size: "S",
    originalPrice: 40.0,
    color: "Red",
    soldOut: "8+",
  },
  {
    id: 24,
    img: "/items/maroon.jpg",
    name: "Maroon",
    price: 34.0,
    size: "M",
    originalPrice: 55.0,
    color: "White",
    soldOut: "100+",
  },
  {
    id: 25,
    img: "/items/lime.jpg",
    name: "Lime",
    price: 29.99,
    size: "XL",
    originalPrice: 47.0,
    color: "Green",
    soldOut: "22+",
  },
  {
    id: 26,
    img: "/items/choco.jpg",
    name: "Choco",
    price: 31.99,
    size: "L",
    originalPrice: 51.0,
    color: "Navy",
    soldOut: "90+",
  },
  {
    id: 27,
    img: "/items/dark.jpg",
    name: "Dark",
    price: 30.5,
    size: "M",
    originalPrice: 48.0,
    color: "White",
    soldOut: "7.8k+",
  },
  {
    id: 28,
    img: "/items/ice.jpg",
    name: "Ice",
    price: 25.0,
    size: "S",
    originalPrice: 38.0,
    color: "Red",
    soldOut: "7.7k+",
  },
  {
    id: 29,
    img: "/items/berry.jpg",
    name: "Berry",
    price: 33.5,
    size: "L",
    originalPrice: 53.0,
    color: "Black",
    soldOut: "7k+",
  },
  {
    id: 30,
    img: "/items/plum.jpg",
    name: "Plum",
    price: 29.0,
    size: "M",
    originalPrice: 45.0,
    color: "Purple",
    soldOut: "7.1k+",
  },
  {
    id: 31,
    img: "/items/stone.jpg",
    name: "Stone",
    price: 27.0,
    size: "S",
    originalPrice: 42.0,
    color: "White",
    soldOut: "10+",
  },
  {
    id: 32,
    img: "/items/charcoal.jpg",
    name: "Charcoal",
    price: 36.0,
    size: "XL",
    originalPrice: 59.0,
    color: "White",
    soldOut: "9k+",
  },
  {
    id: 33,
    img: "/items/lemon.jpg",
    name: "Lemon",
    price: 24.99,
    size: "M",
    originalPrice: 39.0,
    color: "Red",
    soldOut: "55+",
  },
  {
    id: 34,
    img: "/items/brick.jpg",
    name: "Brick",
    price: 35.5,
    size: "L",
    originalPrice: 56.0,
    color: "Blue",
    soldOut: "44+",
  },
  {
    id: 35,
    img: "/items/amber.jpg",
    name: "Amber",
    price: 28.0,
    size: "S",
    originalPrice: 44.0,
    color: "Black",
    soldOut: "68+",
  },
  {
    id: 36,
    img: "/items/smoke.jpg",
    name: "Smoke",
    price: 32.0,
    size: "M",
    originalPrice: 51.0,
    color: "White",
    soldOut: "33+",
  },
  {
    id: 37,
    img: "/items/rose.jpg",
    name: "Rose",
    price: 30.5,
    size: "XL",
    originalPrice: 48.0,
    color: "White",
    soldOut: "2k+",
  },
  {
    id: 38,
    img: "/items/cloud.jpg",
    name: "Cloud",
    price: 33.0,
    size: "M",
    originalPrice: 50.0,
    color: "Green",
    soldOut: "78+",
  },
  {
    id: 39,
    img: "/items/coral.jpg",
    name: "Coral",
    price: 26.5,
    size: "L",
    originalPrice: 43.0,
    color: "White",
    soldOut: "24+",
  },
  {
    id: 40,
    img: "/items/peach.jpg",
    name: "Peach",
    price: 27.99,
    size: "M",
    originalPrice: 41.99,
    color: "Purple",
    soldOut: "33+",
  },
  {
    id: 41,
    img: "/items/olive.jpg",
    name: "Olive",
    price: 29.99,
    size: "L",
    originalPrice: 49.0,
    color: "Black",
    soldOut: "3k+",
  },
  {
    id: 42,
    img: "/items/sand.jpg",
    name: "Sand",
    price: 25.99,
    size: "S",
    originalPrice: 39.99,
    color: "White",
    soldOut: "23+",
  },
  {
    id: 43,
    img: "/items/rust.jpg",
    name: "Rust",
    price: 28.0,
    size: "M",
    originalPrice: 42.5,
    color: "Red",
    soldOut: "7k+",
  },
  {
    id: 44,
    img: "/items/cinnamon.jpg",
    name: "Cinnamon",
    price: 31.0,
    size: "L",
    originalPrice: 52.0,
    color: "Green",
    soldOut: "7.8k+",
  },
  {
    id: 45,
    img: "/items/clay.jpg",
    name: "Clay",
    price: 30.0,
    size: "M",
    originalPrice: 49.0,
    color: "White",
    soldOut: "78+",
  },
  {
    id: 46,
    img: "/items/snow.jpg",
    name: "Snow",
    price: 23.5,
    size: "S",
    originalPrice: 35.0,
    color: "Red",
    soldOut: "99k+",
  },
  {
    id: 47,
    img: "/items/wheat.jpg",
    name: "Wheat",
    price: 27.0,
    size: "XL",
    originalPrice: 42.0,
    color: "Yellow",
    soldOut: "1k+",
  },
  {
    id: 48,
    img: "/items/taupe.jpg",
    name: "Taupe",
    price: 29.5,
    size: "M",
    originalPrice: 45.0,
    color: "White",
    soldOut: "34+",
  },
  {
    id: 49,
    img: "/items/dust.jpg",
    name: "Dust",
    price: 28.5,
    size: "L",
    originalPrice: 44.0,
    color: "Blue",
    soldOut: "99+",
  },
  {
    id: 50,
    img: "/items/fog.jpg",
    name: "Fog",
    price: 26.75,
    size: "S",
    originalPrice: 40.0,
    color: "Blue",
    soldOut: "100k+",
  },
];
